name: Build docker image when pushed releases, main branch
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - "release/**"
    # Sequence of patterns matched against refs/tags
    tags:
      - v2
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          docker build -f Dockerfile -t hongbeenlee/react_query_prac .
          docker run -d -p 3000:3000 hongbeenlee/react_query_prac
          docker login
          docker tag hongbeenlee/react_query_prac:latest hongbeenlee/react_query_prac:latest
          docker push hongbeenlee/react_query_prac:latest
          # etc
