name: Build docker image when pushed releases, main branch
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - "release/**"
    # Sequence of patterns matched against refs/tags
    tags:
      - v2
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: ${{secrets.NAME}}
      ACCESS_TOKEN: ${{secrets.ACCESS}}
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          docker build -f Dockerfile -t cool-docker .
          docker run -d -p 3000:3000 cool-docker
          echo "The Docker Name is: $NAME $ACCESS_TOKEN"
          docker login -u $NAME -p $ACCESS_TOKEN
          docker tag cool-docker:latest hongbeenlee/react_query_prac:latest
          docker push hongbeenlee/react_query_prac:latest
          # etc
